name: Release Language Server
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_artifacts:    
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - binary-name: deep-ink-language-server
            output-name: deep-ink-language-server-linux
            os: ubuntu-latest
          - binary-name: deep-ink-language-server
            output-name: deep-ink-language-server-mac
            os: macos-latest
          - binary-name: deep-ink-language-server.exe
            output-name: deep-ink-language-server-windows.exe
            os: windows-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: mkdir artifacts
      - run: cargo build --release --bins      
      - run: |
          mkdir -p ./artifacts
          mv ./target/release/${{matrix.binary-name}} ./artifacts/${{matrix.output-name}}
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          working_directory: artifacts
          files: |
            ${{matrix.output-name}}
